import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}

// class BinaryNode {
//   constructor(value, left, right) {
//     this.value = value;
//     this.left = left;
//     this.right = right;
//   }
// }
// const root = new BinaryNode("a");
// const b = new BinaryNode("b");
// const c = new BinaryNode("c");
// const d = new BinaryNode("d");
// const e = new BinaryNode("e");
// const f = new BinaryNode("f");

// root.left = b;
// b.left = d;
// b.right = e;
// root.right = c;
// c.left = f;
// console.log(root);
